/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab45.QLDH;

import lab45.TraSua.TraSua;
import lab45.TraSua.Service.TSservice;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author PC
 */
public class QLDH extends javax.swing.JFrame {
    List<TraSua> listND = new ArrayList<>();
    TSservice service = new TSservice();
    DefaultTableModel defaultTable = new DefaultTableModel();
    /**
     * Creates new form QLDH
     */
    public QLDH() {
        initComponents();
        defaultTable = (DefaultTableModel) tblTraSua.getModel(); 
        fillToTable();
        fillToForm(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtMon = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JLabel();
        txtTopping = new javax.swing.JLabel();
        rdoTranChauDen = new javax.swing.JRadioButton();
        rdoThach = new javax.swing.JRadioButton();
        rdoTranChauTrang = new javax.swing.JRadioButton();
        tfSoLuong = new javax.swing.JTextField();
        cbMon = new javax.swing.JComboBox<>();
        txtGhiChu = new javax.swing.JLabel();
        tfGhiChu = new javax.swing.JTextField();
        txtTrangThai = new javax.swing.JLabel();
        cbTrangThai = new javax.swing.JCheckBox();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTraSua = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("QUAN LY DON HANG");

        txtMon.setText("Mon");

        txtSoLuong.setText("So luong");

        txtTopping.setText("Topping");

        rdoTranChauDen.setText("Tran chau den");
        rdoTranChauDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTranChauDenActionPerformed(evt);
            }
        });

        rdoThach.setText("Thach");
        rdoThach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoThachActionPerformed(evt);
            }
        });

        rdoTranChauTrang.setText("Tran chau trang");
        rdoTranChauTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTranChauTrangActionPerformed(evt);
            }
        });

        cbMon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hong tra sua", "sua tuoi tran chau", " ", " " }));

        txtGhiChu.setText("Ghi chu");

        txtTrangThai.setText("Trang thai");

        cbTrangThai.setText("Da thanh toan");

        btnThem.setText("Them");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });

        btnSua.setText("Sua");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tblTraSua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mon", "So luong", "Topping", "Ghi chu", "Trang thai"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblTraSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTraSuaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTraSua);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTopping, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoTranChauDen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoThach))
                            .addComponent(rdoTranChauTrang)
                            .addComponent(tfSoLuong)
                            .addComponent(cbMon, 0, 174, Short.MAX_VALUE)
                            .addComponent(tfGhiChu))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTrangThai)
                        .addGap(18, 18, 18)
                        .addComponent(cbTrangThai))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMon)
                    .addComponent(cbMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoLuong)
                            .addComponent(tfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTopping)
                            .addComponent(rdoTranChauDen)
                            .addComponent(rdoThach))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoTranChauTrang))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGhiChu))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTrangThai)
                    .addComponent(cbTrangThai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoTranChauDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTranChauDenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoTranChauDenActionPerformed

    private void rdoThachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoThachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoThachActionPerformed

    private void rdoTranChauTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTranChauTrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoTranChauTrangActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
    
            TraSua nd = getDuLieuTuForm();
            //KHAI BAO DOI TUONG NGUOIDUNG
//        NguoiDung nd1 = new NguoiDung(txtUser.getText(), txtEmail.getText(), 
//            txtPassword.getText(), CboViTriCV.getSelectedItem().toString(), 
//            rdoUser.isSelected()?1:2, ChkTrangThai.isSelected());
            //GOI SERVICE THEM DOI TUONG NGUOI DUNG MOI
            service.add(nd);
            //do du lieu leen treen bang
            fillToTable();
                  // TODO add your handling code here:
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
    int rowIndex = tblTraSua.getSelectedRow();
        if(rowIndex>=0){
            //thuc hien xoa doi tuong
            //yes:0
            //no:1
            //cancel:2
            int confirm = JOptionPane.showConfirmDialog(this, "Ban co chac muon xoa khong?");
            if(confirm == 0){
                service.delete(rowIndex);
                fillToTable();
            }
        }else {
            JOptionPane.showMessageDialog(this, "Phai chon doi tuong xoa");
        }
           // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblTraSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTraSuaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTraSuaMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLDH().setVisible(true);
            }
        });
    }
    private void fillToTable() {
        listND = service.getListNguoiDung(); //lấy ds người dùng từ service
        //đổi dữ liệu từ dòng đầu tiên
        defaultTable.setRowCount(0);
        for (TraSua nd : listND) {
            defaultTable.addRow(new Object[]{nd.getMon(), nd.getSoLuong(), nd.getToping() == 1 ? "Tran chau den" : "Thach", nd.getGhiChu(), nd.isTrangThai()});
        }
    }
    private void fillToForm(int rowIndex) {
        //lay ra doi tuonng nguoi dung tai rfowindex
        TraSua nd = listND.get(rowIndex);
        //do thuoc tinh username 
        txtMon.setText(nd.getMon());
        tfSoLuong.setText(String.valueOf(nd.getSoLuong()));
      
        //chojn user khi quyen bawng 1
        if (nd.getToping() == 1) {
            rdoTranChauDen.setSelected(true);
        } else {
            rdoThach.setSelected(true);
        }
        tfGhiChu.setText(nd.getGhiChu());
        //do trang thai len ChkTrangThai
        cbTrangThai.setSelected(nd.isTrangThai());
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbMon;
    private javax.swing.JCheckBox cbTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rdoThach;
    private javax.swing.JRadioButton rdoTranChauDen;
    private javax.swing.JRadioButton rdoTranChauTrang;
    private javax.swing.JTable tblTraSua;
    private javax.swing.JTextField tfGhiChu;
    private javax.swing.JTextField tfSoLuong;
    private javax.swing.JLabel txtGhiChu;
    private javax.swing.JLabel txtMon;
    private javax.swing.JLabel txtSoLuong;
    private javax.swing.JLabel txtTopping;
    private javax.swing.JLabel txtTrangThai;
    // End of variables declaration//GEN-END:variables
    private TraSua getDuLieuTuForm() {
        TraSua nd = new TraSua();
        //Lấy giá trị từ txtUser.getText gan cho thuộc tính UserName
        nd.setMon(txtMon.getText().trim());
        nd.setSoLuong(Integer.parseInt(tfSoLuong.getText()));
        nd.setGhiChu(tfGhiChu.getText().trim());
        //C1:
        if (rdoTranChauDen.isSelected()) {
            nd.setTopping(1);
        } else if (rdoThach.isSelected()) {
            nd.setTopping(2);
        }else if (rdoTranChauTrang.isSelected()) {
            nd.setTopping(3);
        } else {
            nd.setTopping(0);
        }
        //C2:
        
        nd.setTrangThai(cbTrangThai.isSelected());
        
        return nd;
    }
}

